[2025-02-03T19:17:19.354+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-03T19:17:19.364+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_dag.collect_raw_stocks manual__2025-02-03T12:05:46-07:00 [queued]>
[2025-02-03T19:17:19.367+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_dag.collect_raw_stocks manual__2025-02-03T12:05:46-07:00 [queued]>
[2025-02-03T19:17:19.367+0000] {taskinstance.py:2866} INFO - Starting attempt 4 of 4
[2025-02-03T19:17:19.372+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): collect_raw_stocks> on 2025-02-03 19:05:46+00:00
[2025-02-03T19:17:19.375+0000] {standard_task_runner.py:72} INFO - Started process 403 to run task
[2025-02-03T19:17:19.377+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_dag', 'collect_raw_stocks', 'manual__2025-02-03T12:05:46-07:00', '--job-id', '126', '--raw', '--subdir', 'DAGS_FOLDER/my_first_dag.py', '--cfg-path', '/tmp/tmp1n7ykcsy']
[2025-02-03T19:17:19.380+0000] {standard_task_runner.py:105} INFO - Job 126: Subtask collect_raw_stocks
[2025-02-03T19:17:19.410+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_dag.collect_raw_stocks manual__2025-02-03T12:05:46-07:00 [running]> on host 48308722451a
[2025-02-03T19:17:19.449+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_dag' AIRFLOW_CTX_TASK_ID='collect_raw_stocks' AIRFLOW_CTX_EXECUTION_DATE='2025-02-03T19:05:46+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-03T12:05:46-07:00'
[2025-02-03T19:17:19.450+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-03T19:17:19.456+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-02-03T19:17:19.457+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 "/opt/***/data_collection/"collect_stocks.py --data_lake_path $DATA_LAKE_PATH --stock_tickers $STOCK_TICKERS --execution_date $EXECUTION_DATE --stock_collect_mode $STOCK_COLLECT_MODE --start_date_missing_values $START_DATE_MISSING_VALUES --end_date_missing_values $END_DATE_MISSING_VALUES']
[2025-02-03T19:17:19.461+0000] {subprocess.py:99} INFO - Output:
[2025-02-03T19:17:20.174+0000] {subprocess.py:106} INFO - Namespace(data_lake_path='/opt/***/data_lake/', stock_tickers='[,AAPL,,MSFT,,AMZN,,META,,NFLX,,GOOG,]', execution_date='2025-02-03', stock_collect_mode='fill_missing', start_date_missing_values='2024-11-01', end_date_missing_values='2025-01-31')
[2025-02-03T19:17:20.175+0000] {subprocess.py:106} INFO -          date        open        high  ...    volume  ticker_name  collect_date
[2025-02-03T19:17:20.175+0000] {subprocess.py:106} INFO - 0  2025-01-29  234.149994  238.690002  ...  30064089         AAPL    2025-01-29
[2025-02-03T19:17:20.175+0000] {subprocess.py:106} INFO - 0  2025-01-29  446.690002  446.880005  ...  11655130         MSFT    2025-01-29
[2025-02-03T19:17:20.179+0000] {subprocess.py:106} INFO - 0  2025-01-29  674.804993  680.289917  ...  11753956         META    2025-01-29
[2025-02-03T19:17:20.181+0000] {subprocess.py:106} INFO - 0  2025-01-29  197.360001  198.459503  ...   7859301         GOOG    2025-01-29
[2025-02-03T19:17:20.185+0000] {subprocess.py:106} INFO - 0  2025-01-29  239.014999  240.360001  ...  16768416         AMZN    2025-01-29
[2025-02-03T19:17:20.186+0000] {subprocess.py:106} INFO - 
[2025-02-03T19:17:20.187+0000] {subprocess.py:106} INFO - [5 rows x 8 columns]
[2025-02-03T19:17:20.188+0000] {subprocess.py:106} INFO - ticker does not exist in the data for [ between 2024-11-01 and 2025-01-31
[2025-02-03T19:17:20.189+0000] {subprocess.py:106} INFO - Traceback (most recent call last):
[2025-02-03T19:17:20.189+0000] {subprocess.py:106} INFO -   File "/opt/***/data_collection/collect_stocks.py", line 125, in <module>
[2025-02-03T19:17:20.189+0000] {subprocess.py:106} INFO -     response = pd.concat(dfs)
[2025-02-03T19:17:20.189+0000] {subprocess.py:106} INFO -                ^^^^^^^^^^^^^^
[2025-02-03T19:17:20.189+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.11/site-packages/pandas/core/reshape/concat.py", line 372, in concat
[2025-02-03T19:17:20.189+0000] {subprocess.py:106} INFO -     op = _Concatenator(
[2025-02-03T19:17:20.191+0000] {subprocess.py:106} INFO -          ^^^^^^^^^^^^^^
[2025-02-03T19:17:20.193+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.11/site-packages/pandas/core/reshape/concat.py", line 429, in __init__
[2025-02-03T19:17:20.193+0000] {subprocess.py:106} INFO -     raise ValueError("No objects to concatenate")
[2025-02-03T19:17:20.193+0000] {subprocess.py:106} INFO - ValueError: No objects to concatenate
[2025-02-03T19:17:20.252+0000] {subprocess.py:110} INFO - Command exited with return code 1
[2025-02-03T19:17:20.258+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-02-03T19:17:20.260+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=etl_dag, task_id=collect_raw_stocks, run_id=manual__2025-02-03T12:05:46-07:00, execution_date=20250203T190546, start_date=20250203T191719, end_date=20250203T191720
[2025-02-03T19:17:20.266+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-03T19:17:20.267+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 126 for task collect_raw_stocks (Bash command failed. The command returned a non-zero exit code 1.; 403)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-02-03T19:17:20.286+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-02-03T19:17:20.295+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-03T19:17:20.297+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
