[2025-01-30T19:36:58.234+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-30T19:36:58.240+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_dag.collect_raw_stocks manual__2025-01-30T12:35:59-07:00 [queued]>
[2025-01-30T19:36:58.246+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_dag.collect_raw_stocks manual__2025-01-30T12:35:59-07:00 [queued]>
[2025-01-30T19:36:58.247+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-30T19:36:58.253+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): collect_raw_stocks> on 2025-01-30 19:35:59+00:00
[2025-01-30T19:36:58.257+0000] {standard_task_runner.py:72} INFO - Started process 266 to run task
[2025-01-30T19:36:58.259+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_dag', 'collect_raw_stocks', 'manual__2025-01-30T12:35:59-07:00', '--job-id', '90', '--raw', '--subdir', 'DAGS_FOLDER/my_first_dag.py', '--cfg-path', '/tmp/tmph2cr50g5']
[2025-01-30T19:36:58.260+0000] {standard_task_runner.py:105} INFO - Job 90: Subtask collect_raw_stocks
[2025-01-30T19:36:58.290+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_dag.collect_raw_stocks manual__2025-01-30T12:35:59-07:00 [running]> on host 48308722451a
[2025-01-30T19:36:58.326+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_dag' AIRFLOW_CTX_TASK_ID='collect_raw_stocks' AIRFLOW_CTX_EXECUTION_DATE='2025-01-30T19:35:59+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-30T12:35:59-07:00'
[2025-01-30T19:36:58.327+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-30T19:36:58.333+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-01-30T19:36:58.333+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /opt/***/data_collection/collect_stocks.py --data_lake_path $DATA_LAKE_PATH --stock_tickers $STOCK_TICKERS --execution_date $EXECUTION_DATE']
[2025-01-30T19:36:58.337+0000] {subprocess.py:99} INFO - Output:
[2025-01-30T19:37:01.176+0000] {subprocess.py:106} INFO - [: No timezone found, symbol may be delisted
[2025-01-30T19:37:01.178+0000] {subprocess.py:106} INFO - Namespace(data_lake_path='/opt/***/data_lake/', stock_tickers='[,AAPL,,MSFT,,AMZN,,META,,NFLX,,GOOG,]', execution_date='2025-01-30')
[2025-01-30T19:37:01.179+0000] {subprocess.py:106} INFO - Empty DataFrame
[2025-01-30T19:37:01.183+0000] {subprocess.py:106} INFO - Columns: [Open, High, Low, Close, Adj Close, Volume]
[2025-01-30T19:37:01.186+0000] {subprocess.py:106} INFO - Index: []
[2025-01-30T19:37:01.186+0000] {subprocess.py:106} INFO - /opt/***/data_lake/raw/csv/20250130_stock_[
[2025-01-30T19:37:01.187+0000] {subprocess.py:106} INFO - Traceback (most recent call last):
[2025-01-30T19:37:01.189+0000] {subprocess.py:106} INFO -   File "/opt/***/data_collection/collect_stocks.py", line 57, in <module>
[2025-01-30T19:37:01.190+0000] {subprocess.py:106} INFO -     save_data(
[2025-01-30T19:37:01.190+0000] {subprocess.py:106} INFO -   File "/opt/***/data_collection/utils.py", line 28, in save_data
[2025-01-30T19:37:01.190+0000] {subprocess.py:106} INFO -     df.to_csv(f"{full_file_name}.csv", index=False)
[2025-01-30T19:37:01.190+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.11/site-packages/pandas/core/generic.py", line 3772, in to_csv
[2025-01-30T19:37:01.190+0000] {subprocess.py:106} INFO -     return DataFrameRenderer(formatter).to_csv(
[2025-01-30T19:37:01.191+0000] {subprocess.py:106} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-01-30T19:37:01.191+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.11/site-packages/pandas/io/formats/format.py", line 1186, in to_csv
[2025-01-30T19:37:01.191+0000] {subprocess.py:106} INFO -     csv_formatter.save()
[2025-01-30T19:37:01.191+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.11/site-packages/pandas/io/formats/csvs.py", line 240, in save
[2025-01-30T19:37:01.191+0000] {subprocess.py:106} INFO -     with get_handle(
[2025-01-30T19:37:01.191+0000] {subprocess.py:106} INFO -          ^^^^^^^^^^^
[2025-01-30T19:37:01.192+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.11/site-packages/pandas/io/common.py", line 737, in get_handle
[2025-01-30T19:37:01.192+0000] {subprocess.py:106} INFO -     check_parent_directory(str(handle))
[2025-01-30T19:37:01.192+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.11/site-packages/pandas/io/common.py", line 600, in check_parent_directory
[2025-01-30T19:37:01.192+0000] {subprocess.py:106} INFO -     raise OSError(rf"Cannot save file into a non-existent directory: '{parent}'")
[2025-01-30T19:37:01.192+0000] {subprocess.py:106} INFO - OSError: Cannot save file into a non-existent directory: '/opt/***/data_lake/raw/csv'
[2025-01-30T19:37:01.252+0000] {subprocess.py:110} INFO - Command exited with return code 1
[2025-01-30T19:37:01.259+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-01-30T19:37:01.262+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=etl_dag, task_id=collect_raw_stocks, run_id=manual__2025-01-30T12:35:59-07:00, execution_date=20250130T193559, start_date=20250130T193658, end_date=20250130T193701
[2025-01-30T19:37:01.268+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-30T19:37:01.268+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 90 for task collect_raw_stocks (Bash command failed. The command returned a non-zero exit code 1.; 266)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-01-30T19:37:01.290+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-01-30T19:37:01.303+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-30T19:37:01.307+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
