[2025-01-30T19:33:32.369+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-30T19:33:32.375+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_dag.collect_raw_books manual__2025-01-30T12:22:46-07:00 [queued]>
[2025-01-30T19:33:32.378+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_dag.collect_raw_books manual__2025-01-30T12:22:46-07:00 [queued]>
[2025-01-30T19:33:32.378+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 2
[2025-01-30T19:33:32.383+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): collect_raw_books> on 2025-01-30 19:22:46+00:00
[2025-01-30T19:33:32.385+0000] {standard_task_runner.py:72} INFO - Started process 122 to run task
[2025-01-30T19:33:32.387+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_dag', 'collect_raw_books', 'manual__2025-01-30T12:22:46-07:00', '--job-id', '84', '--raw', '--subdir', 'DAGS_FOLDER/my_first_dag.py', '--cfg-path', '/tmp/tmpwz0b51so']
[2025-01-30T19:33:32.390+0000] {standard_task_runner.py:105} INFO - Job 84: Subtask collect_raw_books
[2025-01-30T19:33:32.413+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_dag.collect_raw_books manual__2025-01-30T12:22:46-07:00 [running]> on host 48308722451a
[2025-01-30T19:33:32.456+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_dag' AIRFLOW_CTX_TASK_ID='collect_raw_books' AIRFLOW_CTX_EXECUTION_DATE='2025-01-30T19:22:46+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-30T12:22:46-07:00'
[2025-01-30T19:33:32.457+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-30T19:33:32.463+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-01-30T19:33:32.463+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /opt/***/data_collection/collect_books.py --data_lake_path $DATA_LAKE_PATH --open_library_ids $OPEN_LIBRARY_IDS --execution_date $EXECUTION_DATE']
[2025-01-30T19:33:32.467+0000] {subprocess.py:99} INFO - Output:
[2025-01-30T19:33:33.591+0000] {subprocess.py:106} INFO - https://openlibrary.org/works/.json
[2025-01-30T19:33:33.599+0000] {subprocess.py:106} INFO - Error occurred in the request. It returned code: 404
[2025-01-30T19:33:33.601+0000] {subprocess.py:106} INFO -  {'error': 'notfound', 'key': '/works/'}
[2025-01-30T19:33:33.602+0000] {subprocess.py:106} INFO - /opt/***/data_lake/raw/json/20250130_book_
[2025-01-30T19:33:33.663+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-01-30T19:33:33.675+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-30T19:33:33.676+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_dag, task_id=collect_raw_books, run_id=manual__2025-01-30T12:22:46-07:00, execution_date=20250130T192246, start_date=20250130T193332, end_date=20250130T193333
[2025-01-30T19:33:33.711+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-30T19:33:33.721+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-01-30T19:33:33.722+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
